name: petut
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.10
  google_sign_in: ^6.1.4
  flutter_svg: ^2.0.7
  image_picker: ^1.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  intl: ^0.19.0 
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  geocoding: ^2.1.0

dependency_overrides:
  firebase_auth_web: ^5.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/petut.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/4939569d-6a3c-4878-8960-803e5521f119.jpg
    - assets/doctor.jpg
    - assets/animations/Catloader.json