name: petut
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.10
  google_sign_in: ^6.1.4
  flutter_svg: ^2.0.7
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  intl: ^0.19.0
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  geocoding: ^2.1.0
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.8.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  onesignal_flutter: ^5.3.4
  curved_navigation_bar: ^1.0.6
  fluttermoji: ^1.0.2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  firebase_database: 11.3.10
  
dependency_overrides:
  firebase_auth_web: ^5.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/petut.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/images/petut.png
    - assets/dogg.jpg
    - assets/birdd.jpg
    - assets/cattt.jpg
    - assets/toyy.jpg
    - assets/models/
    - assets/models/labels.txt
    - assets/models/model_unquant.tflite