// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6pr6a6y63LvKpauCkonCqyV66WAeJEeg',
    appId: '1:724593819082:web:7d5ab9881bc9de39c8a333',
    messagingSenderId: '724593819082',
    projectId: 'petut-55f40',
    authDomain: 'petut-55f40.firebaseapp.com',
    storageBucket: 'petut-55f40.firebasestorage.app',
    measurementId: 'G-JDSBQXNWX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOnnLV7boUQ91MS-RtpLdI61Zs_64l2M',
    appId: '1:724593819082:android:7a616cb3ed7934dfc8a333',
    messagingSenderId: '724593819082',
    projectId: 'petut-55f40',
    storageBucket: 'petut-55f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-dRm5CWcSHwrLFKW3NVYg5_CUSRNnaGU',
    appId: '1:724593819082:ios:01dd47672e64a1b1c8a333',
    messagingSenderId: '724593819082',
    projectId: 'petut-55f40',
    storageBucket: 'petut-55f40.firebasestorage.app',
    iosBundleId: 'com.example.petut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-dRm5CWcSHwrLFKW3NVYg5_CUSRNnaGU',
    appId: '1:724593819082:ios:01dd47672e64a1b1c8a333',
    messagingSenderId: '724593819082',
    projectId: 'petut-55f40',
    storageBucket: 'petut-55f40.firebasestorage.app',
    iosBundleId: 'com.example.petut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6pr6a6y63LvKpauCkonCqyV66WAeJEeg',
    appId: '1:724593819082:web:d9b17be1a92536f4c8a333',
    messagingSenderId: '724593819082',
    projectId: 'petut-55f40',
    authDomain: 'petut-55f40.firebaseapp.com',
    storageBucket: 'petut-55f40.firebasestorage.app',
    measurementId: 'G-T7P9S4TGJ8',
  );
}
